"""
Meta-Genesis Generated Agent
Auto-generated by the Meta-Genesis Autonomous Agent System
Uses TinyFish/Mino API for cloud-based web automation
"""

import requests
import json
import os
from datetime import datetime

def run_agent():
    """Main agent execution function using TinyFish/Mino API"""

    print(f"[{datetime.now().isoformat()}] Agent starting...")

    # Get API key from environment
    api_key = os.environ.get('AGENTQL_API_KEY')
    if not api_key:
        raise Exception('AGENTQL_API_KEY environment variable not set')

    # Target URL
    target_url = "{{TARGET_URL}}"
    
    # Goal for the automation
    goal = "{{GOAL}}"

    print(f"[{datetime.now().isoformat()}] Calling TinyFish/Mino API...")
    print(f"[{datetime.now().isoformat()}] Target: {target_url}")
    print(f"[{datetime.now().isoformat()}] Goal: {goal}")

    try:
        # Call TinyFish/Mino API
        response = requests.post(
            'https://mino.ai/v1/automation/run',
            headers={
                'X-API-Key': api_key,
                'Content-Type': 'application/json'
            },
            json={
                'url': target_url,
                'goal': goal
            },
            timeout=60
        )

        if response.status_code == 200:
            data = response.json()
            
            # Structure results
            results = {
                'data': data.get('result', {}),
                'timestamp': datetime.now().isoformat(),
                'url': target_url,
                'goal': goal,
                'success': True
            }

            # Output results
            print(f"[{datetime.now().isoformat()}] Results:")
            print(json.dumps(results, indent=2))

            # Save to file
            with open('agent_output.json', 'w') as f:
                json.dump(results, f, indent=2)

            print(f"[{datetime.now().isoformat()}] Agent completed successfully")
            return results
        else:
            error_msg = f"API Error: {response.status_code} - {response.text}"
            print(f"[{datetime.now().isoformat()}] {error_msg}")
            raise Exception(error_msg)

    except requests.exceptions.Timeout:
        print(f"[{datetime.now().isoformat()}] Error: Request timed out")
        raise
    except Exception as e:
        print(f"[{datetime.now().isoformat()}] Error: {str(e)}")
        raise

if __name__ == "__main__":
    run_agent()
